
version: 2

models:
  - name: dim_awards
    description: "The dimension table of the awards"
    columns:
      - name: awards_key
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: people_key
        description: "The key of the people"
        tests:
          - not_null
      - name: year
        description: "the year of the awards"
      - name: league
        description: "the league of the awards"

  - name: dim_schools
    description: "The dimension table of the schools"
    columns:
      - name: school_key
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: school_name
        description: "The full name of the school"
        tests:
          - not_null
      - name: school_city
        description: "sdf"
      - name: school_state
        description: "asda"
      - name: school_country
        description: "saf"
  
  - name: dim_people
    description: "The dimension table of the people"
    columns:
      - name: people_key
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: school_key
        description: "The unique key of the school associated to the people"
        tests:
          - unique
          - not_null
      - name: birth_year
        description: The birth year of the people
      - name: birth_month
        description: The birth month of the people
      - name: birth_day
        description: The birth day of the people
      - name: birth_country
        description: The country birth of the people
      - name: birth_state
        description: The state birth of the people
      - name: birth_city
        description: The city birth of the people
      - name: death_year
        description: The year death of the people
      - name: death_month
        description: The month death of the people
      - name: death_day
        description: The day death of the people
      - name: death_country
        description: The country death of the people
      - name: death_state
        description: The state death of the people
      - name: death_city
        description: The city death of the people
      - name: name_first
        description: The first name of the people
      - name: name_last
        description: The last name of the people
      - name: name_given
        description: The given name of the people
      - name: weight_in_pounds
        description: The body weight of the people in pounds
      - name: weight_in_kgs
        description: The body weight of the people in kilograms
      - name: height_in_inches
        description: The body height of the people in inches
      - name: height_in_cm
        description: The body height of the people in centimeters
      - name: bats
        description: The batting side of the people
      - name: throws
        description: The throwing hand of the people
      - name: debut_date
        description: The date of the debut of the people
      - name: final_game_date
        description: The date of the final game of the people
  
  - name: dim_seasons
    description: "The dimension table of the people"
    columns:
      - name: season_key
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: number_of_matches
        description: The number of matches occured during that season per team

  - name: dim_teams
    description: "The dimension table of the teams"
    columns:
      - name: team_key
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: franchise_name
        description: The name of the franchises
      - name: ballpark
        description: The name of the ballpark
      - name: team_city
        description: The city of the team
      - name: team_state
        description: The state of the team
      - name: team_country
        description: The country of the team

  - name: fact_batting
    description: "The dimension table of the batting statistics"
    columns:
      - name: people_key
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: team_key
        description: The unique key of the teams
      - name: season_key
        description: The unique key of seasons
      - name: games_played
        description: The number of game played
      - name: at_bat
        description: The number of At Bat
      - name: run
        description: The number of Run
      - name: hit
        description: The number of Hit
      - name: double_base_hit
        description: The number of Double Base Hit
      - name: triple_base_hit
        description: The number of Triple Base Hit
      - name: home_runs
        description: The number of Home Runs
      - name: run_batted_in
        description: The number of Run Batted In
      - name: stolen_bases
        description: The number of Stolen Bases
      - name: base_walking
        description: The number of Base Walks
      - name: strike_outs
        description: The number of Strike Outs
        
